// This file is @generated by prost-build.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct SendMessageRequest {
    #[prost(string, tag = "1")]
    pub target_user_id: ::prost::alloc::string::String,
    #[prost(int32, tag = "2")]
    pub message_type: i32,
    #[prost(bytes = "vec", tag = "3")]
    pub message_body: ::prost::alloc::vec::Vec<u8>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct SendMessageResponse {
    #[prost(bool, tag = "1")]
    pub success: bool,
    #[prost(string, tag = "2")]
    pub error_message: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct BroadcastMessageRequest {
    #[prost(int32, tag = "1")]
    pub message_type: i32,
    #[prost(bytes = "vec", tag = "2")]
    pub message_body: ::prost::alloc::vec::Vec<u8>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct BroadcastMessageResponse {
    #[prost(bool, tag = "1")]
    pub success: bool,
    #[prost(string, tag = "2")]
    pub error_message: ::prost::alloc::string::String,
}
